### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nasergh** [febo/myra#5] opened 2021-11-29 16:54 UTC
Dear Fernando,
when i tried to compile the code I get the below error
```
The syntax of the command is incorrect.
make: *** [src/main/java/myra/AbstractActivity.class] Erreur 1

```
there is another way to compile your code?
thanks

**Comment by febo** [comment] 2021-11-29 19:19
Could you let me know how you are trying to compile the code? I could not reproduce the error that you are getting.

**Comment by nasergh** [comment] 2021-11-29 19:24
Hello,
thanks for your reply,
i work on windows, i install Make command.
and i run "make" or "make -f makefile"
but it gives the error that i give it to you.
how do you compile it?
thanks

**Comment by febo** [comment] 2021-11-29 19:33
I would suggest using Maven (http://maven.apache.org) to compile it on Windows. After installing Maven, just run 'mvn package' to build a jar file.

**Comment by nasergh** [comment] 2021-11-29 21:12
Thanks,
after some tries, i can compile it but! it generates 3 Jar files! with some
other files! and size of it is half of your version but it's work! 
2 questions,
1- did you compile in windows or linux?
2- for tracing the java code, which software is better? (i want to trace line by line and see the variables and ...)

29/11/2021  22:06    <DIR>          apidocs
29/11/2021  22:06    <DIR>          classes
29/11/2021  22:06    <DIR>          generated-sources
29/11/2021  22:06    <DIR>          generated-test-sources
29/11/2021  22:06    <DIR>          javadoc-bundle-options
29/11/2021  22:06    <DIR>          maven-archiver
29/11/2021  22:06             2 073 maven-javadoc-plugin-stale-data.txt
29/11/2021  22:06    <DIR>          maven-status
29/11/2021  22:06         1 321 072 myra-5.0-javadoc.jar
29/11/2021  22:06           289 794 myra-5.0-sources.jar
29/11/2021  22:06           370 310 myra-5.0.jar
29/11/2021  22:06    <DIR>          surefire-reports
29/11/2021  22:06    <DIR>          test-classes

**Comment by febo** [comment] 2021-11-29 22:45
The one that you need is myra-5.0.jar - this one has all the classes. I use a Mac and I suggest Visual Studio Code if you want to debug the code. I will close this issue, you can send me an email if you need any help (you can find it on the paper).

**Closed as completed by febo** 2021-11-29 22:45 UTC
